version: '3.8'

services:
  web_graph:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: flask_graph
    ports:
      - '5000:5000'
    networks:
      - graph_global_net
      - postgres_db_net
    depends_on:
      - pg_db

  pg_db:
    image: postgres:16-alpine3.19
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=graphdb
      - POSTGRES_USER=bauman
      - POSTGRES_PASSWORD=baumanpassword
    ports:
      - '6543:5432'
    networks:
      - postgres_db_net
    
networks:
  graph_global_net:
    name: graph_global_net
    driver: bridge
  postgres_db_net:
    name: postgres_db_net
    driver: bridge
    