version: '3.8'

services:
  web_graph:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: flask_graph
    ports:
      - "5000:5000"
    networks:
      - postgres_db
    depends_on:
      - pg_db
    command: ["/bin/bash", "-c", "python /usr/src/app/fill_db.py"]

  pg_db:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=graphdb
      - POSTGRES_USER=bauman
      - POSTGRES_PASSWORD=baumanpassword
    ports:
      - "6543:5432"
    networks:
      - postgres_db
    
networks:
  postgres_db:
    driver: bridge
    